export const products = [
  {
    id: 1,
    name: "Gucci Aviator Vision",
    brand: "Gucci",
    price: 180,
    description:
      "Une interprétation moderne de la silhouette aviateur emblématique, les lunettes Gucci Aviator Vision allient élégance et précision. Avec une monture métallique dorée légère et des verres antireflets, elles garantissent confort et sophistication tout au long de la journée.",
    frameMaterial: "Métal",
    lensMaterial: "CR-39",
    fit: "Standard",
    shape: "Aviateur",
    polarized: false,
    colors: [
      {
        name: "gray",
        image: "https://my-apis-app.vercel.app/images/vue/la1.webp",
      },
      {
        name: "black",
        image: "https://my-apis-app.vercel.app/images/vue/la2.webp",
      },
    ],
    category: "Homme",
    familly: "Lunettes de vue",
    isNew: true,
  },
  {
    id: 2,
    name: "Oakley Square Frame Pro",
    brand: "Oakley",
    price: 150,
    description:
      "Conçues pour la précision et le confort, les lunettes Oakley Square Frame Pro sont dotées d’une monture O-Matter durable et de verres résistants aux impacts — idéales pour les professionnels actifs qui recherchent performance et style.",
    frameMaterial: "O-Matter",
    lensMaterial: "Polycarbonate",
    fit: "Moyen",
    shape: "Carrée",
    polarized: false,
    colors: [
      {
        name: "black",
        image: "https://my-apis-app.vercel.app/images/vue/lb1.webp",
      },
      {
        name: "gray",
        image: "https://my-apis-app.vercel.app/images/vue/lb2.webp",
      },
    ],
    category: "Homme",
    familly: "Lunettes de vue",
    isNew: true,
  },
  {
    id: 3,
    name: "Prada Hexa Light",
    brand: "Prada",
    price: 210,
    description:
      "Les montures Prada Hexa Light offrent un design géométrique sophistiqué en titane ultra-léger. Leur éclat subtil et leurs plaquettes ergonomiques assurent un confort luxueux et un style distinctif pour toutes les occasions.",
    frameMaterial: "Titane",
    lensMaterial: "Verre",
    fit: "Fin",
    shape: "Hexagonale",
    polarized: true,
    colors: [
      {
        name: "gold",
        image: "https://my-apis-app.vercel.app/images/vue/lc1.webp",
      },
      {
        name: "gray",
        image: "https://my-apis-app.vercel.app/images/vue/lc2.webp",
      },
      {
        name: "pink",
        image: "https://my-apis-app.vercel.app/images/vue/lc3.webp",
      },
      {
        name: "deeppink",
        image: "https://my-apis-app.vercel.app/images/vue/lc4.webp",
      },
    ],
    category: "Homme",
    familly: "Lunettes de vue",
    isNew: false,
  },
  {
    id: 4,
    name: "Dior Velvet Charm",
    brand: "Dior",
    price: 230,
    description:
      "Les lunettes Dior Velvet Charm présentent des tons pastel doux et une monture ronde élégante. Leur fabrication en acétate de qualité garantit durabilité et confort, tandis que le logo doré apporte une touche féminine raffinée.",
    frameMaterial: "Acétate",
    lensMaterial: "CR-39",
    fit: "Large",
    shape: "Ronde",
    polarized: false,
    colors: [
      {
        name: "white",
        image: "https://my-apis-app.vercel.app/images/vue/ld1.webp",
      },
      {
        name: "black",
        image: "https://my-apis-app.vercel.app/images/vue/ld2.webp",
      },
      {
        name: "gray",
        image: "https://my-apis-app.vercel.app/images/vue/ld3.webp",
      },
      {
        name: "red",
        image: "https://my-apis-app.vercel.app/images/vue/ld4.webp",
      },
    ],
    category: "Femme",
    familly: "Lunettes de vue",
    isNew: true,
  },
  {
    id: 5,
    name: "Versace Icon Lady",
    brand: "Versace",
    price: 190,
    description:
      "Audacieuses et emblématiques, les montures Versace Icon Lady dégagent une confiance absolue. Avec leurs accents dorés et leur structure en acétate élégante, elles incarnent puissance et élégance.",
    frameMaterial: "Acétate",
    lensMaterial: "Polycarbonate",
    fit: "Moyen",
    shape: "Papillon",
    polarized: false,
    colors: [
      {
        name: "black",
        image: "https://my-apis-app.vercel.app/images/vue/le.webp",
      },
    ],
    category: "Femme",
    familly: "Lunettes de vue",
    isNew: false,
  },
  {
    id: 6,
    name: "Chanel Oval Muse",
    brand: "Chanel",
    price: 240,
    description:
      "Les lunettes Chanel Oval Muse respirent la sophistication avec leurs contours ovales et leur éclat métallique doux. Parfaites pour les femmes qui apprécient le charme intemporel et le confort absolu.",
    frameMaterial: "Métal",
    lensMaterial: "Verre",
    fit: "Petite",
    shape: "Ovale",
    polarized: true,
    colors: [
      {
        name: "purple",
        image: "https://my-apis-app.vercel.app/images/vue/lf1.webp",
      },
      {
        name: "gray",
        image: "https://my-apis-app.vercel.app/images/vue/lf2.webp",
      },
    ],
    category: "Femme",
    familly: "Lunettes de vue",
    isNew: true,
  },
  {
    id: 7,
    name: "Hugo Boss Violet Edge",
    brand: "Hugo Boss",
    price: 175,
    description:
      "Les Violet Edge de Hugo Boss allient design moderne et savoir-faire de qualité. Leur monture en acétate légère mais résistante les rend parfaites pour un usage quotidien ou professionnel.",
    frameMaterial: "Acétate",
    lensMaterial: "Polycarbonate",
    fit: "Moyen",
    shape: "Wayfarer",
    polarized: false,
    colors: [
      {
        name: "purple",
        image: "https://my-apis-app.vercel.app/images/vue/lg.webp",
      },
    ],
    category: "Femme",
    familly: "Lunettes de vue",
    isNew: false,
  },
  {
    id: 8,
    name: "Polaroid Kids GreenStar",
    brand: "Polaroid",
    price: 85,
    description:
      "Les lunettes Polaroid GreenStar sont spécialement conçues pour les enfants — colorées, résistantes et flexibles. Elles offrent une vision claire et une protection UV complète.",
    frameMaterial: "TR90",
    lensMaterial: "Polycarbonate",
    fit: "Enfant",
    shape: "Rectangulaire",
    polarized: false,
    colors: [
      {
        name: "green",
        image: "https://my-apis-app.vercel.app/images/vue/lh.webp",
      },
    ],
    category: "Enfant",
    familly: "Lunettes de vue",
    isNew: false,
  },
  {
    id: 9,
    name: "RayBan Junior Violet Pop",
    brand: "RayBan",
    price: 95,
    description:
      "Les lunettes RayBan Junior Violet Pop combinent des couleurs ludiques et une protection fiable. Légères et flexibles, elles permettent à chaque enfant d’être à la fois stylé et protégé.",
    frameMaterial: "TR90",
    lensMaterial: "Polycarbonate",
    fit: "Enfant",
    shape: "Ronde",
    polarized: false,
    colors: [
      {
        name: "purple",
        image: "https://my-apis-app.vercel.app/images/vue/li1.webp",
      },
      {
        name: "gray",
        image: "https://my-apis-app.vercel.app/images/vue/li2.webp",
      },
    ],
    category: "Enfant",
    familly: "Lunettes de vue",
    isNew: true,
  },
  {
    id: 10,
    name: "Persol SolarEdge",
    brand: "Persol",
    price: 175,
    description:
      "Fabriquées en Italie, les lunettes de soleil Persol SolarEdge disposent de charnières flexibles emblématiques et de verres polarisés qui éliminent les reflets tout en maintenant des contrastes riches — parfaites pour la conduite et les activités extérieures.",
    frameMaterial: "Métal",
    lensMaterial: "Verre",
    fit: "Large",
    shape: "Carrée",
    polarized: true,
    colors: [
      {
        name: "black",
        image: "https://my-apis-app.vercel.app/images/sun/lsa1.webp",
      },
      {
        name: "gray",
        image: "https://my-apis-app.vercel.app/images/sun/lsa2.webp",
      },
    ],
    category: "Homme",
    familly: "Lunettes de soleil",
    isNew: true,
  },
  {
    id: 11,
    name: "Oakley Horizon Pro",
    brand: "Oakley",
    price: 160,
    description:
      "Conçues pour la performance, les lunettes Oakley Horizon Pro combinent une monture robuste et élégante avec des verres polarisés qui améliorent la visibilité et réduisent les reflets — idéales pour le sport en plein air.",
    frameMaterial: "O-Matter",
    lensMaterial: "Plutonite",
    fit: "Standard",
    shape: "Pilote",
    polarized: true,
    colors: [
      {
        name: "gray",
        image: "https://my-apis-app.vercel.app/images/sun/lsb1.webp",
      },
      {
        name: "brown",
        image: "https://my-apis-app.vercel.app/images/sun/lsb2.webp",
      },
      {
        name: "black",
        image: "https://my-apis-app.vercel.app/images/sun/lsb3.webp",
      },
      {
        name: "blue",
        image: "https://my-apis-app.vercel.app/images/sun/lsb4.webp",
      },
    ],
    category: "Homme",
    familly: "Lunettes de soleil",
    isNew: true,
  },
  {
    id: 12,
    name: "Prada Sun Horizon",
    brand: "Prada",
    price: 190,
    description:
      "Les lunettes Prada Sun Horizon se distinguent par leurs tons dorés chauds et leurs verres dégradés offrant une clarté optimale même sous forte luminosité — l’alliance parfaite entre style et confort.",
    frameMaterial: "Métal",
    lensMaterial: "Verre",
    fit: "Moyen",
    shape: "Aviateur",
    polarized: true,
    colors: [
      {
        name: "yellow",
        image: "https://my-apis-app.vercel.app/images/sun/lsc1.webp",
      },
      {
        name: "brown",
        image: "https://my-apis-app.vercel.app/images/sun/lsc2.webp",
      },
    ],
    category: "Homme",
    familly: "Lunettes de soleil",
    isNew: true,
  },
  {
    id: 13,
    name: "Dior Scarlet Sun",
    brand: "Dior",
    price: 220,
    description:
      "Les lunettes Dior Scarlet Sun capturent l’essence de l’élégance et de la force. Leurs verres rouges dégradés et leurs branches métalliques en font un accessoire raffiné et audacieux.",
    frameMaterial: "Métal",
    lensMaterial: "Polycarbonate",
    fit: "Large",
    shape: "Œil-de-chat",
    polarized: false,
    colors: [
      {
        name: "red",
        image: "https://my-apis-app.vercel.app/images/sun/lse1.webp",
      },
      {
        name: "gray",
        image: "https://my-apis-app.vercel.app/images/sun/lse2.webp",
      },
    ],
    category: "Femme",
    familly: "Lunettes de soleil",
    isNew: true,
  },
  {
    id: 14,
    name: "Polaroid SkyLite Kids",
    brand: "Polaroid",
    price: 80,
    description:
      "Les lunettes Polaroid SkyLite Kids affichent des tons bleu ciel amusants, des verres résistants aux chocs et des branches flexibles. Parfaites pour protéger les yeux des enfants en plein air.",
    frameMaterial: "TR90",
    lensMaterial: "Polycarbonate",
    fit: "Enfant",
    shape: "Ovale",
    polarized: true,
    colors: [
      {
        name: "skyblue",
        image: "https://my-apis-app.vercel.app/images/sun/lsf.webp",
      },
    ],
    category: "Enfant",
    familly: "Lunettes de soleil",
    isNew: true,
  },
  {
    id: 15,
    name: "Gucci Elegant Shade",
    brand: "Gucci",
    price: 210,
    description:
      "Les lunettes Gucci Elegant Shade allient féminité et luxe. Avec leurs lignes douces et leurs verres polarisés de qualité, elles apportent une touche chic et raffinée à chaque look.",
    frameMaterial: "Métal",
    lensMaterial: "Verre",
    fit: "Standard",
    shape: "Papillon",
    polarized: true,
    colors: [
      {
        name: "black",
        image: "https://my-apis-app.vercel.app/images/sun/lsg1.webp",
      },
      {
        name: "brown",
        image: "https://my-apis-app.vercel.app/images/sun/lsg2.webp",
      },
    ],
    category: "Femme",
    familly: "Lunettes de soleil",
    isNew: true,
  },
];
